config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  root to: 'finder#index'

  resources :finder, path: '/customers', only: [:index]

  resources :customers do
    get 'alphabetized' => 'finder#alphabetized', on: :collection

    get 'missing_email' => 'finder#missing_email', on: :collection
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # this was before Part 3
  # validates :full_name, presence: true

  validates_presence_of :full_name, :phone_number

  # validates_length_of :phone_number, :is => 12

  validates_uniqueness_of :email, :case_sensitive => false, :allow_blank => true

  belongs_to :province
end

app/models/province.rb
class Province < ApplicationRecord
  validates_presence_of :name

  has_many :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/finder_controller.rb
class FinderController < ApplicationController

  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(:full_name)
  end

  def missing_email
    @customers = Customer.where(:email => "")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/finder_helper.rb
module FinderHelper
end

app/views/customers/_customer.html.slim
doctype html
html
  head
  .customer

  	h2 = customer.full_name

  	p = image_tag customer.image, height:'200', width:'150'

  	p
  		strong> Phone:
  		= customer.phone_number

    p
      strong> Province:
      = customer.province.blank? ? "None" : customer.province.name

  	p
  		strong> Email:
  		= customer.email_was

  	p
  		strong> Notes:
  		= customer.notes

/ .customer
/        h2 = customer.full_name
/
/        p = image_tag customer.image, height:'200', width:'150'
/
/        p
/           strong> Province:
/           = customer.province.blank? ? "None" : customer.province.name
/
/        p
/           strong> Phone:
/           = customer.phone_number
/
/        - unless @customer.email.blank?
/           p
/            strong> Email:
/            = customer.email_address
/
/        - if(customer.notes.nil?)
/           p
/            strong> Notes:
/        - else
/          p
/            strong> Notes:
/            = customer.notes
/
/        p = link_to 'details', customer

app/views/finder/alphabetized.html.slim
h1 Customers from A-Z

ul
  li = link_to 'All Customers', root_path
ul
  li = link_to 'with Missing Emails', missing_email_customers_path

ul
  = render partial: @customers, collection: @alphabetized

app/views/finder/index.html.slim
#wrapper
  h1 All Customers

  ul
    li = link_to 'From A-Z', alphabetized_customers_path
  ul
    li = link_to 'with Missing Emails', missing_email_customers_path

  ul
    = render partial: @customers

app/views/finder/missing_email.html.slim
h1 Missing Emails

ul
  li = link_to 'All Customers', root_path
ul
  li = link_to 'Customers A-Z', alphabetized_customers_path
  
ul
  = render partial: @customers, collection: @missing_email

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UC7Lopez</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>